Areas/User/Controllers/InvitationsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using WeddingAnniversary.Areas.User.Models;
using WeddingAnniversary.Data;

namespace WeddingAnniversary.Areas.User.Controllers
{
    [Area("User")]
    public class InvitationsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public InvitationsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: User/Invitations
        [Route("User/Invitations")]
        public async Task<IActionResult> Index()
        {
            IEnumerable<Invitation> invitations = await _context.invitations.ToListAsync();
            return View(invitations);
        }

        [HttpGet("{UserName}")]
        [Route("User/Invitations/ViewSingle/{UserName}")]
        [Route("User/Invitations/ViewSingle")]
        public async Task<IActionResult> ViewSingle(string UserName)
        {
            IEnumerable<Invitation> invitations = await _context.invitations.Where(i => i.OwnerEmail == UserName).ToListAsync();
            return View(invitations);
        }

        [HttpGet("{ID}")]
        [Route("User/Invitations/ViewInvitation/{ID}")]
        [Route("User/Invitations/ViewInvitation")]
        public IActionResult ViewInvitation(int ID)
        {
            Invitation invitation = _context.invitations.Where(i => i.Id == ID).FirstOrDefault();
            return View(invitation);
        }

        [HttpGet("{ID}")]
        [Route("User/Invitations/ViewRSVP/{ID}")]
        [Route("User/Invitations/ViewRSVP")]
        public async Task<IActionResult> ViewRSVP(int ID)
        {
            Invitation invitation = _context.invitations.Where(i => i.Id == ID).FirstOrDefault();

            GuestList gList = new GuestList();

            if (invitation.GuestListId == null)
            {
                _context.guestLists.Add(gList);
                await _context.SaveChangesAsync();
                invitation.GuestListId = gList.Id;
                await _context.SaveChangesAsync();
            }
            if (invitation.GuestListId != null)
            {
                Guest g = new Guest();
                g.GuestListId = Convert.ToInt32(invitation.GuestListId);
                return View(g);
            } else
            {
                return NotFound();
            }
        }

        // GET: User/Invitations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var invitation = await _context.invitations
                .Include(i => i.Schedule)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (invitation == null)
            {
                return NotFound();
            }

            return View(invitation);
        }

        // GET: User/Invitations/Create
        [Route("User/Invitations/Create")]
        public IActionResult Create()
        {
            ViewData["ScheduleId"] = new SelectList(_context.schedules, "Id", "Id");
            return View();
        }

        // POST: User/Invitations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Consumes("application/json")]
        [Route("User/Invitations/CreateJson")]
        public async Task<IActionResult> CreateJson()//[FromBody] Invite invitation)
        {
            var reader = new StreamReader(
            Request.Body,
            encoding: Encoding.UTF8,
            detectEncodingFromByteOrderMarks: false
            );
            var bodyString = await reader.ReadToEndAsync();

            var invitation = JsonConvert.DeserializeObject<Invite>(bodyString);


            //string shit = invitation.InvitationIntro;
            Invitation inv = new Invitation();
            inv.InvitationIntro = invitation.InvitationIntro;
            inv.OurStory = invitation.OurStory;
            inv.OwnerEmail = invitation.OwnerEmail;
            inv.RSVPDate = invitation.RSVPDate;
            inv.ScheduleId = invitation.ScheduleId;
            inv.Venue = invitation.Venue;
            inv.VenueLocation = invitation.VenueLocation;
            inv.VenueWebsite = invitation.VenueWebsite;
            inv.WeddingDate = invitation.WeddingDate;
            inv.WeddingName = invitation.WeddingName;
            inv.NotesId = invitation.NotesId == -1 ? null : _context.notes.OrderByDescending(x => x.Id).FirstOrDefault().Id;
            //invitation.Id = _context.invitations.FirstOrDefault() == null ? 1 :  _context.invitations.OrderByDescending(i => i.Id).FirstOrDefault().Id + 1;
            if (ModelState.IsValid)
            {
                _context.Add(inv);
                await _context.SaveChangesAsync();
                //return RedirectToAction(nameof(Index));
                return Json(new { success = true, message = "Create Successful" });
            }
            else
            {
                string errors = "";
                int idx = 1;
                foreach (var modelState in ViewData.ModelState.Values)
                {
                    foreach (ModelError error in modelState.Errors)
                    {
                        errors += idx++ + ": " + error;
                    }
                }
                return Json(new { success = false, message = "Error while creating: " + errors });
            }
            //ViewData["ScheduleId"] = new SelectList(_context.schedules, "Id", "Id", invitation.ScheduleId);
            //return View(invitation);
        }

        [HttpPost]
        [Consumes("application/json")]
        [Route("User/Invitations/UpdateJson")]
        public async Task<IActionResult> UpdateJson()
        {
            var reader = new StreamReader(
            Request.Body,
            encoding: Encoding.UTF8,
            detectEncodingFromByteOrderMarks: false
            );
            var bodyString = await reader.ReadToEndAsync();

            var invitation = JsonConvert.DeserializeObject<Invite>(bodyString);


            //string shit = invitation.InvitationIntro;
            Invitation inv = new Invitation();
            inv.Id = invitation.Id;
            inv.InvitationIntro = invitation.InvitationIntro;
            inv.OurStory = invitation.OurStory;
            inv.OwnerEmail = invitation.OwnerEmail;
            inv.RSVPDate = invitation.RSVPDate;
            inv.ScheduleId = invitation.ScheduleId;
            inv.Venue = invitation.Venue;
            inv.VenueLocation = invitation.VenueLocation;
            inv.VenueWebsite = invitation.VenueWebsite;
            inv.WeddingDate = invitation.WeddingDate;
            inv.WeddingName = invitation.WeddingName;
            inv.NotesId = invitation.NotesId == -1 ? null : _context.notes.OrderByDescending(x => x.Id).FirstOrDefault().Id;
            //invitation.Id = _context.invitations.FirstOrDefault() == null ? 1 :  _context.invitations.OrderByDescending(i => i.Id).FirstOrDefault().Id + 1;
            if (ModelState.IsValid)
            {
                _context.Update(inv);
                await _context.SaveChangesAsync();
                //return RedirectToAction(nameof(Index));
                return Json(new { success = true, message = "Create Successful" });
            }
            else
            {
                string errors = "";
                int idx = 1;
                foreach (var modelState in ViewData.ModelState.Values)
                {
                    foreach (ModelError error in modelState.Errors)
                    {
                        errors += idx++ + ": " + error;
                    }
                }
                return Json(new { success = false, message = "Error while creating: " + errors });
            }
            //ViewData["ScheduleId"] = new SelectList(_context.schedules, "Id", "Id", invitation.ScheduleId);
            //return View(invitation);
        }

        [HttpPost]
        [Consumes("application/json")]
        [Route("User/Invitations/NotesJson")]
        public async Task<IActionResult> NotesJson()
        {
            try
            {
                var reader = new StreamReader(
                Request.Body,
                encoding: Encoding.UTF8,
                detectEncodingFromByteOrderMarks: false
                );
                var bodyString = await reader.ReadToEndAsync();

                IEnumerable<NoteItem> noteItems = JsonConvert.DeserializeObject<IEnumerable<NoteItem>>(bodyString);

                Notes ns = new Notes();
                _context.notes.Add(ns);
                await _context.SaveChangesAsync();
                int ID = ns.Id;

                foreach (NoteItem noteItem in noteItems)
                {
                    noteItem.NotesId = ID;
                    if (_context.noteItems.Where(n => n.NotesId == ID && n.NoteValue == noteItem.NoteValue).Count() <= 0)
                    {
                        _context.Add(noteItem);
                        await _context.SaveChangesAsync();
                    }
                }

                return Json(new { success = true, message = ID.ToString() });
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return Json(new { success = false, message = -1 });
            }
        }

        [HttpPost]
        [Consumes("application/json")]
        [Route("User/Invitations/UpdateNotesJson")]
        public async Task<IActionResult> UpdateNotesJson()
        {
            try
            {

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WeddingAnniversary</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Save The Date</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="User" asp-controller="Invitations" asp-action="ViewSingle" asp-route-UserName="@User.Identity.Name">Invitations</a>
                            </li>
                        }
                        <!--<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>-->
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; Cornelius Frylinck - 2021
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://kit.fontawesome.com/1b297263cb.js" crossorigin="anonymous"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>